### ISSUE TITLE
IllegalParameterValueException happens when there is a comma in the uri for Resources Service.

### ISSUE THREAD

**Issue by aaaakun** [Jaspersoft/jrs-rest-java-client#319]
Code :
OperationResult<ClientResourceListWrapper> result = client
					.authenticate(Constant.ServerInfo.userName, Constant.ServerInfo.password) // username/password
					.resourcesService()
					.resources().parameter(ResourceSearchParameter.FOLDER_URI, "/organizations/dummy/organizations/dummy,13") 
					.parameter(ResourceSearchParameter.RECURSIVE, Constant.API.FALSE)
					.search(); 
			ClientResourceListWrapper clientResourceListWrapper = result.getEntity();

I can use a name contains a comma as an organization name, but I can't get resources using a uri contains a comma.

Looking forward to your reply.

**Comment by tmatveyeva** [comment]
Hello,

What this coma is about? As far as I am aware of it should not be possible to create resource with coma in URI. Since such resource cannot exist, I do not expect any special processing of coma in search. Even if there are any issues with that, it is not related to rest client itself. 

Regards,
Tetyana
